const config = {
    cocApiToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjQxYjJiZGUwLTExNjctNGZlMy04Y2Y0LTY4MmZlZDY0NTQ3NyIsImlhdCI6MTY3OTg0NDg1Niwic3ViIjoiZGV2ZWxvcGVyL2ZhNmE4ZDQ5LWZjNzQtM2M5Ny00MDUyLTYwMjlkNWQxOGQ4ZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEzNi4xNTguNTcuNDYiXSwidHlwZSI6ImNsaWVudCJ9XX0.1nuaSksm-u9DR8fOvTK9SVhS4yRsc9YBorkmDCDXkVolewmTEAxmiX9-jqnrjcOQWFs-SlYWHwaAofEzGe6PPw",
    cocUrl: "https://api.clashofclans.com/v1"
}
/**
 * @param {string} sample
 */

export default config